### <font color='blue'>**注意這邊由numpy建立的array型別為numpy.ndarray**</font>
而非一般的list，在基本操作上相似但有許多用法不同

Outline:
* Creating Arrays
* Using arrays and scalars
* Indexing (slicing) Arrays

# Creating Arrays

In [1]:
import numpy as np

In [2]:
my_list1 = [1, 2, 3, 4]

In [26]:
# 用list建立Array
my_array1 = np.array(my_list1)

In [27]:
print type(my_array1)
my_array1

<type 'numpy.ndarray'>


array([1, 2, 3, 4])

In [24]:
my_list2 = [[1, 2, 3], [4, 5, 6], [6, 6, 6], [7, 7, 7]]
my_array2 = np.array(my_list2)

In [28]:
# Array Size
my_array2.shape

(4, 3)

In [29]:
# Elements的data type
my_array2.dtype

dtype('int64')

In [46]:
# 用0建立Array
zeros_array = np.zeros(5)

In [48]:
print zeros_array
print zeros_array.dtype # 注意data type是float

[ 0.  0.  0.  0.  0.]
float64


In [49]:
# 用1建立Array
np.ones([2, 3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [50]:
# 建立empty Array
# 跟np.zeros的差別是，所有elements都沒有被初始化
# 使用的時機: 建立一個Array，而其中所有值都將在之後才設定
np.empty([3, 3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [44]:
# 建立對角為1的2-D Array
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [45]:
# 用range建立Array
np.arange(2, 5)

array([2, 3, 4])

# Using arrays and scalars
對array中的所有elements做四則運算

In [51]:
import numpy as np

In [65]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [72]:
arr1 + 1

array([[2, 3],
       [4, 5]])

In [66]:
arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [67]:
arr1 - arr2

array([[-4, -4],
       [-4, -4]])

In [68]:
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [69]:
1.0 / arr1

array([[ 1.        ,  0.5       ],
       [ 0.33333333,  0.25      ]])

In [70]:
arr1 ** 2

array([[ 1,  4],
       [ 9, 16]])

# Indexing Arrays

In [79]:
arr = np.arange(0, 11)

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 基本的index / slice操作，如同list

In [83]:
arr[3]

3

In [84]:
arr[1:5]

array([1, 2, 3, 4])

In [85]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

In [91]:
arr[::-1]

array([10,  9,  8,  7,  6,  5, 10, 10, 10, 10,  0])

## slice的區段，可以直接賦值改變原array (list不可)
因為ndarray上的slice動作，是做類似建立區段的reference到elements的動作

而非複製elements到新ndarray，所以會一起改變

In [87]:
arr[1:5] = 10

In [88]:
arr

array([ 0, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [92]:
arr[:] = 5

In [93]:
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## 複製array
真正用原elements建立一個新的ndarray，不影響原ndarray

In [94]:
arr_copy = arr.copy()

In [95]:
arr_copy

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## 2d array

In [99]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1][1]

5

In [100]:
# Slicing
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [119]:
arr2d = np.zeros((10, 10))
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [114]:
# Size
arr2d.shape[1]

10

In [118]:
for i in range(arr2d.shape[1]):
    arr2d[i] = i
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [120]:
# 選取index 2, 4 ,6
arr2d[[2, 4 ,6]]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [121]:
# 選取index 5, 3
arr2d[[5, 3]]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])