Outline:
* Array Transposition
* Universal Array Function

# Array Transposition

In [3]:
import numpy as np

In [2]:
# reshape
arr = np.arange(50).reshape([10, 5])

In [3]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [18]:
# Transpose
arr.T # 等同於arr.transpose()

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [7]:
# Dot product (內積/點積)
np.dot(arr.T, arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [4]:
# 3D matrix
arr3d = np.arange(24).reshape([2, 3, 4])

In [15]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [20]:
# Transpose 3D matrix
arr3d.transpose() # 2x3x4 -> 4x3x2

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [5]:
# Transpose 3D matrix - 現在還不太懂什麼意思
arr3d.transpose([1, 0, 2])

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
# Swap axes - 現在還不太懂什麼意思
arr.swapaxes(0, 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

# Universal Array Function
完整清單: [available-ufuncs](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs)

In [38]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
# 開根號
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [40]:
# 指數 (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [41]:
# 亂數產生常態分配
A = np.random.randn(10)
A

array([-0.19933159, -0.19879302,  0.7991674 ,  0.93363185, -0.63585215,
       -1.2070786 ,  0.56273448, -0.2313076 ,  1.13352254,  0.79670687])

In [42]:
B = np.random.randn(10)
B

array([-0.70427698, -2.29647721, -0.15697431,  0.58536812,  1.88602324,
        0.54531354, -0.23671691,  0.30134702,  2.05406932,  0.53914356])

In [43]:
# 相加
np.add(A, B) # 等同於A + B

array([-0.90360857, -2.49527023,  0.64219309,  1.51899997,  1.25017109,
       -0.66176506,  0.32601757,  0.07003942,  3.18759186,  1.33585043])

In [49]:
# 找出較大的值
np.maximum(A, B)

array([-0.19933159, -0.19879302,  0.7991674 ,  0.93363185,  1.88602324,
        0.54531354,  0.56273448,  0.30134702,  2.05406932,  0.79670687])